name: Deploy AKS with Pulumi

on:
  push:
    paths:
      - 'infrastructure/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Pulumi CLI
        run: |
          wget https://github.com/pulumi/pulumi/releases/latest/download/pulumi-v3.92.0-linux-x64.tar.gz
          tar -xzf pulumi-v3.92.0-linux-x64.tar.gz
          sudo mv pulumi/* /usr/local/bin/

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: infrastructure

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Pulumi Preview
        uses: pulumi/actions@v4
        with:
          command: preview
          stack-name: shared-aks/prod
          work-dir: infrastructure
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Up
        uses: pulumi/actions@v4
        with:
          command: up
          stack-name: shared-aks/prod
          work-dir: infrastructure
          args: --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # Uncomment the destroy step only if you actually want to destroy resources
      # - name: Pulumi Destroy
      #   uses: pulumi/actions@v4
      #   with:
      #     command: destroy
      #     stack-name: shared-aks/prod
      #     work-dir: infrastructure
      #     args: --yes
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}