name: Deploy AKS with Pulumi

on:
  push:
    paths:
      - 'infrastructure/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt
        working-directory: infrastructure

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Configure Pulumi
        working-directory: infrastructure
        run: |
          pulumi stack select shared-aks/prod --non-interactive || pulumi stack init shared-aks/prod
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Preview
        working-directory: infrastructure
        run: |
          pulumi preview --stack shared-aks/prod --non-interactive
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Pulumi Up
        working-directory: infrastructure
        run: |
          pulumi up --stack shared-aks/prod --yes
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      # - name: Pulumi Destroy
      #   working-directory: infrastructure
      #   run: |
      #     pulumi destroy --stack shared-aks/prod --yes
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
